spring:
  datasource:
    url: jdbc:postgresql://tramway.proxy.rlwy.net:58103/railway
    username: postgres
    password: PMHvBGARvGKznyupPTtUcpkcxqRrQfPa
  data:
    redis:
      url: redis://127.0.0.1:6379
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1081033611706-0evi744gc5lli3rh6r3n4sir25ft3u4d.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:5173/login/oauth2/code/google"
            scope:
              - openid
              - profile
              - email

  mail:
    host: smtp.mail.ru
    port: 465
    username: nurlan.aydin06nnn@mail.ru
    password: a9ERebgrYZf7W0jW3d7y
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: false
email:
  from: nurlan.aydin06nnn@mail.ru
cloudinary:
  cloud_name: dcawzx4kp
  api_key: 963419412157174
  api_secret: of8ffqL1wIZlmczO6RGM28qiktY
