spring:
  datasource:
    url: jdbc:postgresql://tramway.proxy.rlwy.net:58103/railway
    username: postgres
    password: PMHvBGARvGKznyupPTtUcpkcxqRrQfPa
  data:
    redis:
      url: redis://127.0.0.1:6379
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1081033611706-0evi744gc5lli3rh6r3n4sir25ft3u4d.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:5173/login/oauth2/code/google"
            scope:
              - openid
              - profile
              - email

  mail:
    username: suhansun13@gmail.com
    password: tmei mwud dcix kmpc
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

cloudinary:
  cloud_name: dcawzx4kp
  api_key: 963419412157174
  api_secret: of8ffqL1wIZlmczO6RGM28qiktY
